name: Sync Presets
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          APPSCRIPT_URL: ${{ secrets.APPSCRIPT_URL }}
        run: curl -L "$APPSCRIPT_URL" -o public.json
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update presets"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit"
          fi
