name: Sync Presets
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -L "https://script.google.com/macros/s/AKfycbzdYJePYPJP6KABSCpYQfIAb04eXpq6BK9E0HW9OhUYGQkHy0zs71SSnKewEyChtKixbw/exec" -o public.json
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public.json
          git diff-index --quiet HEAD || git commit -m "Update presets"
          git push
