name: Sync Presets
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      run: curl -L "${{ secrets.APPSCRIPT_URL }}" -o public.json
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public.json
          git diff-index --quiet HEAD || git commit -m "Update presets"
          git push
